version: "3.8"
services:
  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  identity.api:
    image: identity_api_image
    build:
      context: .
      dockerfile: Dockerfile
volumes:
  identitydb_volume:
