version: "3.8"
services:
  identitydb:
    container_name: identitydb
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - identitydb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
  identity.api:
    container_name: identity_api
    restart: on-failture
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=identitydb,1433;Database=IdentityDb;User=sa; Password=Password12*"
    ports:
      - "5000:80"
    depends_on:
      - identitydb